# -*- coding: utf-8 -*-
"""ICS_DES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OZJnMgf3LfutxH_GjvmM_tWbw1yB5Pt5
"""

import pyDes
from time import time

!pip install pyDes

data = input("Please enter plain text for encryption:")
keystring=input("Enter 16/24 byte string for key generation:")

k = pyDes.triple_des(keystring, padmode=pyDes.PAD_PKCS5)
e = k.encrypt(data)
print ("cipher text: %r" % e)

print ("plain text: %r" % k.decrypt(e))
t1 = time()
for i in range(1000):
     e = k.encrypt(data)
t2 = time()
print("Elapsed time for 1,000 encryptions: {:0.3f}s".format(t2 - t1))